apiVersion: v1
kind: secrets
metadata:
  name: db-secrets
data:
# mysql username and password
  username: root
  password: RXhwZW5zZUFwcEAxCg==
  user: expense
# kubectl create -f 10-secrets.yaml
# kubectl get secrets
# kubectl describe secrets db-secrets
# kubectl get secrets db-secrets -o yaml
# kubectl get secrets db-secrets -o json
# kubectl get secrets db-secrets -o jsonpath='{.data.username}' | base64 --decode

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user