apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
    - name: mysql
      image: mysql
      envFrom:
        - secretRef:
            name: db-secrets
        
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: password
        # - name: MYSQL_ROOT_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: username
        # - name: MYSQL_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: user
  # kubectl create -f 11-pod-secrets.yaml
  # kubectl get pods
  # kubectl describe pod pod-secrets
  # kubectl exec -it pod-secrets -- bash
