apiVersion: v1
kind: Service
metadata:
  name: myService
spec:
  selector:
    app: myApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# kube-proxy will forward the request to the correct pod based on the service selector
# The service selector is the label of the pod
