apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer # This will create a load balancer in the cloud, and works only in the cloud.
  selector: # this is the label of the pod
    name: frontend
    environment: dev
    project: myproject
  ports:
    - protocol: TCP
      port: 80 # port on which service will be exposed
      targetPort: 80 # port on which pod is running
      nodePort: 30009