apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "efs-dynamic"
---
apiVersion: v1 
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    app: efs-dynamic-pod
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
spec:
  containers:
  - name: efs-dynamic-container
    image: nginx
    volumeMounts:
    - name: efs-dynamic-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-dynamic-volume
    persistentVolumeClaim:
      claimName: efs-dynamic-claim
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic-service
spec: 
  selector:
    app: efs-dynamic-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer