apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - expense
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   nodeSelectorTerms:
      #   - matchExpressions:
      #     - key: project
      #       operator: In
      #       values:
      #       - expense
  containers:
  - name: with-node-affinity
    image: nginx
  # remove the tolerations if it is preferredDuringSchedulingIgnoredDuringExecution
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"

# kubectl apply -f K8s-resource/selector/nodeAffinity.yaml
# kubectl get pods
# kubectl describe pod with-node-affinity
# kubectl get pods -o wide
